import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1200, height: 1000 } });
const errors = [];
page.on('pageerror', e => errors.push('PAGEERROR: ' + e.message));
page.on('console', m => { if (m.type() === 'error') errors.push('CONSOLE: ' + m.text()); });
await page.goto('https://styleoftokyo-pages.vercel.app/maedaoshi-wp-preview.html', { waitUntil: 'networkidle' });
await page.waitForTimeout(2000);
const bodyText = await page.evaluate(() => document.body.innerText.length);
const hasMsWrap = await page.evaluate(() => !!document.querySelector('.ms-wrap'));
const childCount = await page.evaluate(() => document.querySelector('.ms-wrap')?.children.length || 0);
const html = await page.content();
console.log('innerText length:', bodyText);
console.log('.ms-wrap exists:', hasMsWrap);
console.log('.ms-wrap children:', childCount);
console.log('HTML length:', html.length);
console.log('Errors:', errors);
await page.screenshot({ path: 'preview-check-full.png', fullPage: true });
await browser.close();
